parser: typescript-eslint-parser
plugins:
  - typescript
  - babel

  - react

  - unicorn
  - import
extends:
  - plugin:unicorn/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/electron

  - prettier
  - prettier/react

rules:
  ##########
  # CUSTOM #
  ##########
  insecure-random: error
  ts-no-use-before-define:
    - error
    - functions: false
      variables: false
      typedefs: false

  ###########
  # PLUGINS #
  ###########
  # TYPESCRIPT
  typescript/interface-name-prefix:
    - error
    - always
  typescript/no-angle-bracket-type-assertion: error
  typescript/explicit-member-accessibility: error
  typescript/no-unused-vars: error
  ## blocked by https://github.com/nzakas/eslint-plugin-typescript/pull/23
  # typescript/member-ordering: error
  ##

  # BABEL
  babel/no-invalid-this: error

  # REACT
  react/jsx-boolean-value:
    - error
    - always
  react/jsx-key: error
  react/jsx-no-bind: error
  react/no-string-refs: error

  # UNICORN
  unicorn/explicit-length-check: off
  unicorn/catch-error-name: off

  # IMPORT
  import/first: error
  import/no-amd: error
  import/extensions: error
  import/no-commonjs: error
  import/no-duplicates: error
  import/no-absolute-path: error
  import/newline-after-import: error
  import/no-webpack-loader-syntax: error
  import/no-extraneous-dependencies: error

  import/no-dynamic-require: warn
  import/no-mutable-exports: warn

  ## blocked by https://github.com/eslint/typescript-eslint-parser/issues/345
  import/named: off
  import/namespace: off
  import/export: off
  ##

  ###########
  # BUILTIN #
  ###########
  curly: error
  ## blocked by https://github.com/eslint/typescript-eslint-parser/issues/344
  # indent:
  #   - error
  #   - 2
  #   - SwitchCase: 1
  ##

  no-new-wrappers: error
  no-redeclare:
    - error
    - builtinGlobals: true
  no-eval: error
  no-sync: error
  no-unused-expressions: error
  no-var: error
  prefer-const: error
  eqeqeq:
    - error
    - smart

  ###########
  # SPECIAL #
  ###########
  no-restricted-syntax:
    - error
    # no-default-export
    - selector: ExportDefaultDeclaration
      message: Use of default exports is forbidden

parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true

settings:
  import/extensions:
    - .js
    - .ts
    - .tsx
  import/resolver:
    node:
      extensions:
        - .js
        - .ts
        - .tsx
  import/parsers:
    espree:
      - .js
